# Generated by Django 4.2 on 2023-05-05 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_id_product_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='id',
        ),
    ]
